apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterops-global
  namespace: kommander
spec:
  interval: 5s
  path: ./kustomizations/global
  prune: true
  sourceRef:
   kind: GitRepository
   name: gitops-demo
   namespace: kommander
