apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- global-kustomization.yaml
- workspaces-kustomization.yaml
- workspaces-rbac-kustomization.yaml
- projects-kustomization.yaml
