apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterops-workspace-applications
  namespace: kommander
spec:
  interval: 5s
  path: ./kustomizations/workspaces/applications
  prune: true
  sourceRef:
   kind: GitRepository
   name: gitops-demo
   namespace: kommander
