apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Project
metadata:
  annotations:
    kommander.mesosphere.io/description: "I am batman"
    kommander.mesosphere.io/display-name: batman
  name: batman
  namespace: batcave
spec:
  namespaceName: batman
  placement:
    clusterSelector:
      matchLabels:
        env: test
  workspaceRef:
    name: batcave
