apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Project
metadata:
  annotations:
    kommander.mesosphere.io/description: "Hellio I am Robin"
    kommander.mesosphere.io/display-name: robin
  name: batman
  namespace: batcave
spec:
  namespaceName: robin
  placement:
    clusterSelector:
      matchLabels:
        env: test
  workspaceRef:
    name: batcave
