apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Project
metadata:
  annotations:
    kommander.mesosphere.io/description: "I am green goblin"
    kommander.mesosphere.io/display-name: green-goblin
  name: green-goblin
  namespace: oscorp
spec:
  namespaceName: green-goblin
  placement:
    clusterSelector:
      matchLabels:
        env: test
  workspaceRef:
    name: oscorp