apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Project
metadata:
  annotations:
    kommander.mesosphere.io/description: "I am spiderman"
    kommander.mesosphere.io/display-name: spiderman
  name: spiderman
  namespace: oscorp
spec:
  namespaceName: spiderman
  placement:
    clusterSelector:
      matchLabels:
        env: test
  workspaceRef:
    name: oscorp